# Use Java 17 (compatible with Spring Boot)
FROM eclipse-temurin:17-jdk

# Create app folder
WORKDIR /app

# Copy JAR file generated by Maven
COPY target/*.jar app.jar

# Expose the port Spring Boot runs on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
